# Site settings
title: The Suhua Blog 
email: 1079087531@qq.com
description: Hi, This is Suhua Blog.
  
source: docs
url: http://aisuhua.github.io/
baseurl: "/blog" 

zhihu_username: aisuhua
segmentfault_username: aisuhua
github_username:  aisuhua
cnblogs_username:  isuhua

# github_avatar:  https://avatars0.githubusercontent.com/u/11390617?v=3&s=460
github_avatar: http://sfault-avatar.b0.upaiyun.com/890/673/890673660-55531aaec3a2a_huge256

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true

sass:
  sass_dir: ../
  style: compressed
  
highlighter: rouge 

paginate: 10

excerpt_separator: "\n\n\n"

version: 0.0.1

use_local_static: true # set the value 'true' if you want to use local static files such as js/css.

assects_url: http://7xj8ix.com1.z0.glb.clouddn.com/assets # the url of static files in qiniu

category_title_prefix: "The Suhua Blog: "
category_dir: category
